### ISSUE TITLE
Limit user input to correct counties and municipalities (avoid spelling mistakes, etc)

### ISSUE THREAD

**Issue by michhkh** [Ketilmar/asistobe-vegvesen#13]
Avoid spelling mistakes from user input - maybe with a warning.
Only allow actual counties and municipalities to be written.
Avoid empty user input as well.

**Comment by Ketilmar** [comment]
Are spelling mistakes not handled by the form as input fields are linked to a json file with name and number? As you type you get suggestions. I guess we could have the input field turn red if no match, or something.

Empty input i'm trying to catch in fetch function.

**Comment by michhkh** [comment]
Yes, or we could also refuse an input/fetch if the input isn't correct, so that it's not possible to attempt an invalid fetch.

**Comment by Ketilmar** [comment]
I'm closing this issue as it relates to earlier React code. These things are now handled in fetch switch as it fails with default switch.
